Algoritmo "Exemplo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Marcos Monteiro
// Descrição   : Solicita o endereço ao usuário e imprime na tela
// Autor(a)    : Bruno Apostólico
// Data atual  : 23/05/2022
Var
// Seção de Declarações das variáveis 
endereco: caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Digite seu endereço: ")
   leia(endereco)
   
   escreva("Seu endereço é: " + endereco)

Fimalgoritmo